// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma", // DBのテーブル定義ファイルのパス
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // url: process.env["DATABASE_URL"], // データベースへの接続情報
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"], // マイグレーション用は直接接続を使用（poolerではなくポート5432）
  },
});
